title: "egartley.net"
subtitle: "Americanism, not globalism, will be our credo!"
baseurl: ""
url: "https://egartley.net"
include: ["_pages", "docs"]
exclude:
  - run.bat
  - google0ba76d0f2cd1b895.html
  - robots.txt
  - README.md